#!/usr/bin/env bash
# Auto-generated by install-local.sh — do not edit manually.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
export HOME="/Users/cuiliangjing"

# Source LLM env for signal detection
[ -f "/Users/cuiliangjing/.cortex/env" ] && source "/Users/cuiliangjing/.cortex/env"
export LLM_API_KEY="${LLM_API_KEY:-}"

cd "/Users/cuiliangjing/Projects/cortex" || exit 1
exec "/opt/homebrew/bin/uv" run cortex serve
