#!/usr/bin/env bash
# Auto-generated by install-local.sh — do not edit manually.
export PATH="/Users/cuiliangjing/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
export HOME="/Users/cuiliangjing"

# Source LLM env for semantic routing
[ -f "/Users/cuiliangjing/.cortex/env" ] && source "/Users/cuiliangjing/.cortex/env"

cd "/Users/cuiliangjing/Projects/cortex-wechat" || exit 1
exec "/Users/cuiliangjing/.bun/bin/bun" run start:ilink
